name: Create Meetup Event and Share

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type'
        required: true
        type: choice
        options:
          - speaker
          - social
        default: 'speaker'
      event_title:
        description: 'Event title'
        required: true
        type: string
      event_description:
        description: 'Event description'
        required: true
        type: string
      event_datetime_venue:
        description: 'Event date/time and venue (format: YYYY-MM-DD HH:MM|Venue Name|Address)'
        required: true
        type: string
      num_speakers:
        description: 'Number of speakers (ignored for social events)'
        required: false
        type: string
        default: '1'
      sponsor_info:
        description: 'Sponsor name and URL (format: Name|URL, speaker events only)'
        required: false
        type: string
      share_platforms:
        description: 'Platforms to share to (comma-separated: slack,linkedin)'
        required: false
        type: string
        default: 'slack,linkedin'
      event_url:
        description: 'Meetup event URL (enter after creating event manually)'
        required: false
        type: string

jobs:
  create-and-share-event:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build application
      run: go build -o meetop ./cmd/meetop

    - name: Generate templates and share to social media
      env:
        # Meetup Group configuration
        MEETUP_GROUP_URLNAME: ${{ secrets.MEETUP_GROUP_URLNAME }}
        
        # Event inputs
        EVENT_TYPE: ${{ github.event.inputs.event_type }}
        EVENT_TITLE: ${{ github.event.inputs.event_title }}
        EVENT_DESCRIPTION: ${{ github.event.inputs.event_description }}
        EVENT_DATETIME_VENUE: ${{ github.event.inputs.event_datetime_venue }}
        NUM_SPEAKERS: ${{ github.event.inputs.num_speakers }}
        SPONSOR_INFO: ${{ github.event.inputs.sponsor_info }}
        SHARE_PLATFORMS: ${{ github.event.inputs.share_platforms }}
        EVENT_URL: ${{ github.event.inputs.event_url }}
      run: ./meetop

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: meetop-logs
        path: meetop.log